import {listModules,listLessons,listMaterials,listQuizzes,listManagedQuestions,courseAssignments,courseLiveClasses,learningResourceUrl} from './api.ts';
import {assessmentWorkspace,openAssessment} from './assessment-api.ts';
import {action,el,emptyState} from './ui.ts';
export async function coursePreview(id:string):Promise<HTMLElement>{
 const [modules,lessons,quizzes,assignments,classes,externalQuiz,externalAssignment]=await Promise.all([listModules(id),listLessons(id),listQuizzes(id),courseAssignments(id),courseLiveClasses(id),assessmentWorkspace('quiz'),assessmentWorkspace('assignment')]);const host=el('div',{class:'app-stack'});
 for(const module of modules){const panel=el('section',{class:'card'},el('div',{class:'card__body'},el('h2',{},module.title)));const body=panel.querySelector('div')!;for(const lesson of lessons.filter(l=>l.module_id===module.id)){body.append(el('h3',{},lesson.title),el('p',{},`${lesson.is_published?'Published':'Draft'} · ${lesson.description??''}`));if(lesson.youtube_video_id)body.append(el('a',{class:'btn',href:`https://www.youtube.com/watch?v=${encodeURIComponent(lesson.youtube_video_id)}`,target:'_blank',rel:'noopener noreferrer'},'Review YouTube lesson'));for(const material of await listMaterials(lesson.id))body.append(el('button',{class:'btn',type:'button',onclick:action(async()=>{const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const url=await learningResourceUrl(material.storage_path);if(tab)tab.location.href=url;else location.assign(url);}catch(error){tab?.close();throw error;}})},`Review material: ${material.title}`));}host.append(panel);}
 for(const quiz of quizzes){const questions=await listManagedQuestions(quiz.id);host.append(el('section',{class:'card'},el('div',{class:'card__body'},el('h2',{},quiz.title),el('p',{},quiz.instructions??''),...questions.map(q=>el('div',{},el('strong',{},q.prompt),el('p',{},`${q.options?.join(' · ')??''} · Correct answer: ${q.correct_answer} · ${q.points} marks`))))));}
 for(const assignment of assignments)host.append(el('section',{class:'card'},el('div',{class:'card__body'},el('h2',{},assignment.title),el('p',{},assignment.instructions??'No instructions supplied'),el('p',{},`${assignment.max_score} marks · ${assignment.is_published?'Published':'Draft'}`))));
 for(const assessment of [...externalQuiz.assessments,...externalAssignment.assessments].filter(a=>a.course_id===id))host.append(el('section',{class:'card'},el('div',{class:'card__body'},el('h2',{},String(assessment.title)),el('p',{},String(assessment.instructions)),el('button',{type:'button',class:'btn',onclick:action(()=>openAssessment(String(assessment.id)))},'Review external assessment'))));
 for(const live of classes)host.append(el('p',{},`${live.title} · ${live.scheduled_date} ${live.start_time} ${live.timezone??'Africa/Lagos'} · ${live.status}`));return host.children.length?host:emptyState('No course content yet');
}
