import {listCourses,listModules} from '../api.ts';
import {assessmentWorkspace,assessmentAction,openAssessment} from '../assessment-api.ts';
import type {AdminRow} from '../admin-api.ts';
import {action,el,emptyState,field,input,page,select,textarea,fmtDateTime} from '../ui.ts';
const role=location.pathname.split('/')[1] as 'student'|'tutor'|'admin';const kind=location.pathname.includes('assignments')||new URLSearchParams(location.search).get('kind')==='assignment'?'assignment':'quiz';
const str=(r:AdminRow,key:string)=>String(r[key]??'');
function form(title:string,fields:Record<string,HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>,run:(values:AdminRow)=>Promise<unknown>):HTMLElement{
 const node=el('form',{class:'card admin-form'},el('h2',{},title),...Object.entries(fields).map(([key,value])=>field(({course_id:'Course',module_id:'Module',destination:'Google Form or Drive link',due_at:'Deadline',max_score:'Maximum marks',passing_score:'Pass mark (%)',is_published:"Publish status",results_published:"Show marks to students"} as Record<string,string>)[key]??key.replaceAll('_',' '),value)),el('button',{type:'submit',class:'btn btn--primary'},title.startsWith('Publish')?'Publish assessment':'Save'));
 node.addEventListener('submit',event=>{event.preventDefault();void action(async()=>{const button=node.querySelector<HTMLButtonElement>('button')!;button.disabled=true;try{const values:AdminRow={};for(const [key,value]of Object.entries(fields))values[key]=key==='due_at'&&value.value?new Date(value.value).toISOString():value.value;await run(values);location.reload();}finally{button.disabled=false;}})(event);});return node;
}
void page({role,title:"Linked quizzes and assignments",base:`/${role}`,active:location.pathname.includes('assignments')?'/assignments/':location.pathname.includes('quizzes')?'/quizzes/':'/assessments/'},async content=>{
 const data=await assessmentWorkspace(kind);const courseFilter=new URLSearchParams(location.search).get('course');if(courseFilter)data.assessments=data.assessments.filter(a=>a.course_id===courseFilter);content.append(el('h1',{},"Quizzes and assignments"),el('div',{class:'btn-row'},el('a',{class:'btn',href:`/${role}/assessments/?kind=quiz`},'Quizzes'),el('a',{class:'btn',href:`/${role}/assessments/?kind=assignment`},'Assignments'),el('a',{class:'btn',href:role==='student'?`/student/${kind==='quiz'?'practice-quizzes':'written-assignments'}/`:`/${role}/courses/`},role==='student'?"Practice in the app":"Manage course")),el('p',{},"Open your tutor’s link and complete the work. Then enter your answer or submission reference below. Your tutor checks the work and releases your marks. Opening the link alone does not count as completing it."));
 if(role!=='student'){
  const courses=await listCourses();const fields=(row?:AdminRow)=>({course_id:select(courses.map(c=>({value:c.id,label:c.title}))),module_id:select([{value:'',label:'Choose a module'}]),title:input({required:true,maxlength:200,value:row?str(row,'title'):''}),instructions:textarea({maxlength:5000,rows:4,value:row?str(row,'instructions'):''}),destination:input({required:true,type:'url',value:row?str(row,'destination'):'',placeholder:'https://forms.gle/… or https://drive.google.com/…'}),due_at:input({type:'datetime-local',value:row?.due_at?localDateTime(str(row,'due_at')):''}),max_score:input({required:true,type:'number',min:1,max:100000,value:row?str(row,'max_score'):'100'}),passing_score:input({required:true,type:'number',min:0,max:100,value:row?str(row,'passing_score'):'50'}),is_published:select([{value:'false',label:'Draft'},{value:'true',label:'Published'}])});
  const creation={...fields(),kind:select([{value:'quiz',label:'Quiz'},{value:'assignment',label:'Assignment'}])};creation.kind.value=kind;if(courseFilter)creation.course_id.value=courseFilter;creation.is_published.value='true';const refreshModules=async()=>{const modules=await listModules(creation.course_id.value);creation.module_id.replaceChildren(...modules.map(m=>el('option',{value:m.id},m.title)));};creation.course_id.addEventListener('change',()=>{void action(refreshModules)(new Event('change'));});await refreshModules();content.append(form(`Publish an external ${kind}`,creation,values=>assessmentAction('create',null,values))); 
  for(const row of data.assessments){const f=fields(row);f.course_id.value=str(row,'course_id');const modules=await listModules(f.course_id.value);f.module_id.replaceChildren(el('option',{value:''},"Whole course"),...modules.map(m=>el('option',{value:m.id},m.title)));f.module_id.value=str(row,'module_id');f.is_published.value=String(row.is_published);f.course_id.disabled=true;f.max_score.disabled=true;f.passing_score.disabled=true;content.append(el('details',{class:'card'},el('summary',{},`${str(row,'title')} · ${row.is_published?'Published':'Draft'}`),form('Edit assessment',f,v=>assessmentAction('edit',str(row,'id'),v))));}
 }else if(!data.assessments.length)content.append(emptyState(`No external ${kind==='quiz'?'quizzes':'assignments'} published yet`));
 const studentGroups=new Map<string,HTMLElement>();if(role==='student'&&kind==='quiz'&&data.assessments.length)content.append(el('h2',{},"Latest quizzes and assignments"));
 for(const row of role==='student'?data.assessments:[]){const submission=data.submissions.find(s=>s.assessment_id===row.id);let target=content;if(kind==='quiz'){const key=String(row.course_id)+':'+String(row.module_id);if(!studentGroups.has(key)){const modules=await listModules(str(row,'course_id'));const group=el('details',{class:'student-module-library',open:studentGroups.size===0},el('summary',{},`${str(row,'course')} · ${modules.find(m=>m.id===row.module_id)?.title??'Course quizzes'}`));studentGroups.set(key,group);content.append(group);}target=studentGroups.get(key)!;}target.append(el('section',{class:'card'},el('div',{class:'card__body'},el('h2',{},str(row,'title')),el('p',{},str(row,'course')),el('p',{},str(row,'instructions')),el('p',{},`${row.max_score} marks · pass ${row.passing_score}%${row.due_at?' · Due '+fmtDateTime(str(row,'due_at')):''}`),el('button',{class:'btn',type:'button',onclick:action(()=>openAssessment(str(row,'id')))},'Open assessment'),submission?el('p',{},submission.results_published?`Result: ${submission.score} / ${row.max_score} · ${str(submission,'feedback')}`:"Submitted. Waiting for your tutor to confirm the result."):null,submission?.status==='graded'?el('p',{},"Graded answers cannot be submitted again."):form('Submit completion reference or answer',{response:textarea({required:true,maxlength:5000,rows:4,value:submission?str(submission,'response'):''})},v=>assessmentAction('submit',str(row,'id'),v)))));}
 if(role!=='student'){content.append(el('h2',{},"Submissions and past results"));if(!data.submissions.length)content.append(emptyState('No submissions yet'));for(const row of data.submissions){const release=select([{value:'false',label:"Keep marks hidden"},{value:'true',label:"Show marks to the student"}]);release.value=String(row.results_published);content.append(el('section',{class:'card'},el('div',{class:'card__body'},el('h3',{},`${str(row,'student')} · ${str(row,'title')}`),el('p',{},str(row,'response')),form(row.status==='graded'?"Correct result":"Check and grade",{score:input({required:true,type:'number',min:0,max:Number(row.max_score),step:'0.5',value:str(row,'score')}),feedback:textarea({maxlength:5000,value:str(row,'feedback')}),results_published:release},v=>assessmentAction('grade',str(row,'id'),v)))));}}
});

function localDateTime(value:string):string{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
