import {courseLiveClasses,listCourses,pendingSubmissions,tutorCourseMetrics,tutorDashboardStats,tutorStudentActivity,setLiveClassStatus} from '../api.ts';
import {assessmentWorkspace} from '../assessment-api.ts';
import {learningWorkspace,joinClass} from '../learning-api.ts';
import type {Course,LiveClass,TutorCourseMetric,TutorStudentActivity} from '../types.ts';
import {action,el,emptyState,fmtClock,fmtRelative,icon,initials,page,platformLabel,progressBar,setChildren} from '../ui.ts';
void page({role:'tutor',title:"Tutor dashboard",base:'/tutor',active:'/dashboard/'},async(content)=>{
 const [stats,metrics,activity,courses,submissions,hub,externalQuizzes,externalAssignments]=await Promise.all([tutorDashboardStats(),tutorCourseMetrics(),tutorStudentActivity(),listCourses(),pendingSubmissions(),learningWorkspace(),assessmentWorkspace('quiz'),assessmentWorkspace('assignment')]);
 const externalPending=[...externalQuizzes.submissions,...externalAssignments.submissions].filter(s=>s.status==='submitted').length;
 const classes=(await Promise.all(metrics.map(c=>courseLiveClasses(c.id)))).flat().filter(c=>(c.status==='scheduled'&&c.scheduled_date>=new Date().toISOString().slice(0,10))||c.status==='live').sort((a,b)=>(a.scheduled_date+a.start_time).localeCompare(b.scheduled_date+b.start_time));
 setChildren(content,el('h1',{class:'learning-screen-title'},"Tutor dashboard"),el('div',{class:'dash-stats dash-stats--four'},stat("My courses",String(stats.total_courses),`${stats.published_courses} published`,'book'),stat("Total students",String(stats.total_students),'Enrolled across your courses','users'),stat("Live classes",String(classes.length),"Scheduled and live now",'video'),stat("Waiting for grading",String(submissions.length+externalPending),"Work waiting to be checked",'edit')),
 el('div',{class:'tutor-layout'},coursesCard(metrics),classesCard(classes,courses),activityCard(activity),reviewsCard(submissions.length,hub.pending_quiz_reviews,hub.unanswered,externalPending)));
});
function stat(label:string,value:string,hint:string,name:string):HTMLElement{return el('section',{class:'dash-stat'},el('span',{class:'dash-stat__icon'},icon(name)),el('div',{class:'dash-stat__body'},el('span',{class:'dash-stat__label'},label),el('strong',{class:'dash-stat__value'},value),el('small',{class:'dash-stat__hint'},hint)));}
function head(title:string,href:string):HTMLElement{return el('div',{class:'dash-card__head'},el('h2',{},title),el('a',{class:'dash-card__link',href},"View all"));}
function coursesCard(courses:TutorCourseMetric[]):HTMLElement{return el('section',{class:'dash-card tutor-course-panel'},head("My courses",'/tutor/courses/'),courses.length?el('ul',{class:'tutor-course-list'},...courses.slice(0,5).map((c,i)=>el('li',{},el('img',{src:c.thumbnail_url&&/^https:\/\//.test(c.thumbnail_url)?c.thumbnail_url:`/assets/img/course/${i%6+1}.jpg`,alt:'',class:'learning-mini-cover',loading:'lazy'}),el('div',{},el('a',{href:`/tutor/course/?id=${encodeURIComponent(c.id)}`},el('strong',{},c.title)),el('small',{},`${c.students} students`)),progressBar(c.progress),el('small',{},`${c.progress}%`)))):emptyState('No courses yet',el('a',{class:'btn btn--primary',href:'/tutor/courses/'},'Create a course')));}
function classesCard(classes:LiveClass[],courses:Course[]):HTMLElement{return el('section',{class:'dash-card tutor-live-panel'},head("Upcoming live classes",'/tutor/live/'),classes.length?el('ul',{class:'learning-class-list'},...classes.slice(0,3).map(c=>el('li',{class:'learning-class-row'},el('span',{class:'learning-class-icon'},icon('video')),el('div',{class:'learning-class-copy'},el('strong',{},c.title),el('small',{},courses.find(x=>x.id===c.course_id)?.title??'Your course'),el('small',{},`${c.scheduled_date} · ${fmtClock(c.start_time)} ${c.timezone??'Africa/Lagos'}`)),el('span',{class:'learning-provider'},platformLabel(c.platform)),el('button',{class:'btn btn--sm learning-outline',type:'button',onclick:action(async()=>{await joinClass(c.id);if(c.status==='scheduled')await setLiveClassStatus(c.id,'live');})},c.status==='live'?'Open':'Start')))):emptyState('No upcoming classes',el('a',{href:'/tutor/live/',class:'btn'},'Schedule a class')));}
function activityCard(rows:TutorStudentActivity[]):HTMLElement{return el('section',{class:'dash-card tutor-activity-panel'},head("Recent student activity",'/tutor/activity/'),rows.length?el('ul',{class:'learning-feed'},...rows.slice(0,4).map(r=>el('li',{},el('span',{class:'learning-student-avatar'},initials(r.student_name)),el('div',{},el('strong',{},r.student_name),el('small',{},`${r.action} · ${r.course_title}`)),el('time',{},fmtRelative(r.occurred_at))))):emptyState('No student activity yet'));}
function reviewsCard(assignments:number,attempts:number,questions:number,external:number):HTMLElement{const rows=[["Assignment submissions",assignments,"Review",'/tutor/grading/','edit'],["Quiz attempts",attempts,"Review",'/tutor/attempts/','check-circle'],["Google Form and Drive submissions",external,"Review",'/tutor/assessments/','edit'],["Student questions",questions,"Answer",'/tutor/questions/','message']] as const;return el('section',{class:'dash-card tutor-review-panel'},el('h2',{},"Pending reviews"),el('ul',{class:'learning-pending'},...rows.map(([label,count,button,href,name])=>el('li',{},el('span',{class:'learning-feed-icon'},icon(name)),el('span',{},label),el('strong',{},String(count)),el('a',{href,class:'btn btn--sm learning-outline'},button)))));}
