import {bootstrapDatabase,as} from '/Users/kakanfoinn/Documents/Projects/icanpath-academy/icanpath/scripts/pg-harness.mjs';
import {writeFileSync} from 'node:fs';
const db=await bootstrapDatabase();
const {rows:tables}=await db.query(`select tablename,rowsecurity from pg_tables where schemaname='public' order by tablename`);
const {rows:policies}=await db.query(`select tablename,policyname,roles,cmd,qual,with_check from pg_policies where schemaname in ('public','storage') order by tablename,policyname`);
const {rows:functions}=await db.query(`select p.oid::regprocedure::text as signature,p.prosecdef,p.proconfig,has_function_privilege('anon',p.oid,'execute') as anon_execute,has_function_privilege('authenticated',p.oid,'execute') as authenticated_execute from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' order by 1`);
const {rows:grants}=await db.query(`select grantee,table_name,privilege_type from information_schema.role_table_grants where table_schema='public' and grantee in ('anon','authenticated') order by table_name,grantee,privilege_type`);
writeFileSync('/private/tmp/icanpath-security-inventory.json',JSON.stringify({tables,policies,functions,grants},null,2));
const tutor=(await db.query(`insert into auth.users(email,raw_user_meta_data) values('audit-tutor@example.test','{"requested_role":"tutor"}') returning id`)).rows[0].id;
const student=(await db.query(`insert into auth.users(email,raw_user_meta_data) values('audit-student@example.test','{}') returning id`)).rows[0].id;
await db.query(`update profiles set status='active' where id=$1`,[tutor]);
const courseResult=await as(db,'authenticated',tutor,`insert into courses(title) values('Audit only') returning id`);
if(!courseResult.ok) throw new Error(JSON.stringify(courseResult));
const course=courseResult.rows[0].id;
await db.query(`update courses set status='published' where id=$1`,[course]);
await db.query(`insert into course_enrollments(course_id,student_id) values($1,$2)`,[course,student]);
const quizResult=await as(db,'authenticated',tutor,`insert into quizzes(course_id,title,is_published,time_limit_minutes,due_at,attempt_limit) values('${course}','Audit late quiz',true,1,now()-interval '1 day',3) returning id`);
if(!quizResult.ok) throw new Error(JSON.stringify(quizResult));
const quiz=quizResult.rows[0].id;
const question=(await db.query(`insert into quiz_questions(quiz_id,prompt,question_type,correct_answer,points) values($1,'Synthetic question','short_answer','yes',1) returning id`,[quiz])).rows[0].id;
console.log('Expired quiz start:',JSON.stringify(await as(db,'authenticated',student,`select start_quiz_attempt('${quiz}') as attempt`)));
await db.query(`update quiz_attempts set started_at=now()-interval '1 hour' where quiz_id=$1`,[quiz]);
console.log('Expired timer submission:',JSON.stringify(await as(db,'authenticated',student,`select submit_quiz_attempt('${quiz}','{"${question}":"yes"}'::jsonb) as result`)));
console.log('Start another attempt:',JSON.stringify(await as(db,'authenticated',student,`select start_quiz_attempt('${quiz}') as attempt`)));
await db.query(`update course_enrollments set status='cancelled' where course_id=$1 and student_id=$2`,[course,student]);
console.log('Submission after enrollment removed:',JSON.stringify(await as(db,'authenticated',student,`select submit_quiz_attempt('${quiz}','{"${question}":"yes"}'::jsonb) as result`)));
console.log('Anonymous contact writes across distinct emails:');
for(let i=0;i<4;i++) console.log(i,JSON.stringify(await as(db,'anon',null,`select submit_contact_message('Synthetic audit','audit${i}@example.test','','Audit','Synthetic test only') as id`)));
console.log('Anonymous raw private content read:',JSON.stringify(await as(db,'anon',null,`select * from lessons`)));
const module=(await db.query(`insert into modules(course_id,title) values($1,'Audit module') returning id`,[course])).rows[0].id;
const lesson=(await db.query(`insert into lessons(course_id,module_id,title,is_published) values($1,$2,'Unpublished audit lesson',false) returning id`,[course,module])).rows[0].id;
await db.query(`update course_enrollments set status='active' where course_id=$1 and student_id=$2`,[course,student]);
console.log('Progress for unpublished lesson:',JSON.stringify(await as(db,'authenticated',student,`select set_lesson_progress('${lesson}',100)`)));
console.log('Stored progress:',JSON.stringify((await db.query(`select completed,progress_percentage from lesson_progress where lesson_id=$1`,[lesson])).rows));
console.log('Inventory:',tables.length,'tables',policies.length,'policies',functions.filter(f=>f.prosecdef).length,'definers');
console.log('Definers with anon execute:',JSON.stringify(functions.filter(f=>f.prosecdef&&f.anon_execute)));
console.log('Definers without search_path:',JSON.stringify(functions.filter(f=>f.prosecdef&&!f.proconfig?.some(c=>c.startsWith('search_path=')))));
await db.close();
