import {learningWorkspace,recordEarning} from '../learning-api.ts';
import {dateRange,dateMetrics,downloadReport,money,operate,searchAdmin,workspace,type AdminRow} from '../admin-api.ts';
import {reviewQueueCourses,tutorApplications,listCourses,listProfiles,notifications,markNotificationRead,markAllNotificationsRead,setLiveClassStatus} from '../api.ts';
import {supabase,unwrap} from '../supabase.ts';
import {config} from '../config.ts';
import {action,el,emptyState,field,input,page,select,setChildren,textarea,toast,fmtDateTime} from '../ui.ts';
const section=window.location.pathname.split('/').filter(Boolean)[1]??'reports';
const titles:Record<string,string>={enrollments:'Enrolments',live:"Live classes",notifications:'Notifications',reports:"Reports and analytics",audit:"Audit logs",settings:"System settings",messages:'Messages',payments:'Payments & Refunds',moderation:"Approvals and reports",search:'Search'};
const str=(r:AdminRow,k:string)=>String(r[k]??'—');
const button=(label:string,run:()=>Promise<void>)=>el('button',{type:'button',class:'btn btn--sm',onclick:action(run)},label);
function table(rows:AdminRow[],columns:[string,string][],controls?:(r:AdminRow)=>HTMLElement):HTMLElement{
 if(!rows.length)return emptyState('Nothing here yet','New records will appear here when they are created.');
 return el('div',{class:'app-table-wrap'},el('table',{class:'app-table'},el('thead',{},el('tr',{},...columns.map(([,label])=>el('th',{},label)),controls?el('th',{},'Actions'):null)),el('tbody',{},...rows.map(r=>el('tr',{},...columns.map(([k])=>el('td',{},k==='amount_minor'?money(Number(r[k])/100):k.endsWith('_at')?fmtDateTime(String(r[k])):str(r,k))),controls?el('td',{},controls(r)):null)))));
}
function formPanel(title:string,fields:Record<string,HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>,save:(values:AdminRow)=>Promise<void>):HTMLElement{
 const form=el('form',{class:'card admin-form'});form.append(el('h2',{},title),...Object.entries(fields).map(([key,node])=>field(({student_id:'Student',course_id:'Course',tutor_id:'Tutor',payment_id:'Verified receipt',original_entry_id:'Original earning',recipient_id:'Recipient'} as Record<string,string>)[key]??key.replaceAll('_',' '),node)),el('button',{class:'btn btn--primary',type:'submit'},title==='Enrol a student'?'Enrol student':title==='Platform settings'?'Save setting':'Save'));
 form.addEventListener('submit',event=>{event.preventDefault();void action(async()=>{const submit=form.querySelector<HTMLButtonElement>('button[type=submit]');if(submit)submit.disabled=true;try{const values:AdminRow={};for(const [key,node] of Object.entries(fields))values[key]=node.value;await save(values);toast('Saved.');window.location.reload();}finally{if(submit)submit.disabled=false;}})(event);});return form;
}
const reload=()=>window.location.reload();
void page({role:'admin',title:titles[section]??'Administration',base:'/admin',active:`/${section}/`},async(content,session)=>{
 content.classList.add('admin-workspace-page');
 const heading=el('div',{class:'section-head section-head--split'},el('h1',{},titles[section]??'Administration'),el('a',{href:'/admin/dashboard/',class:'btn btn--sm'},'Dashboard'));content.append(heading);
 if(section==='search'){
  const q=new URLSearchParams(location.search).get('q')?.trim()??'';const results=q.length>=2?await searchAdmin(q):[];
  content.append(el('p',{},`Results for “${q}”`),table(results,[['title','Name'],['kind','Type']],r=>el('a',{class:'btn btn--sm',href:r.kind==='user'?`/admin/users/?q=${encodeURIComponent(str(r,'title'))}`:`/admin/course/?id=${encodeURIComponent(str(r,'course_id'))}`},'Open')));return;
 }
 if(section==='notifications'){
  const rows=await notifications();content.append(button("Mark all read",async()=>{await markAllNotificationsRead();reload();}),table(rows as unknown as AdminRow[],[['title','Title'],['body','Message'],['created_at','Received']],r=>r.read_at?el('span',{},'Read'):button("Mark as read",async()=>{await markNotificationRead(str(r,'id'));reload();})));return;
 }
 const data=await workspace();content.append(el('p',{class:'admin-list-note'},'Manage learning records and platform activity. Lists show the latest 200 records.'));
 if(section==='enrollments'){
 const [profiles,courses]=await Promise.all([listProfiles(),listCourses()]);
 content.append(formPanel('Enrol a student',{student_id:select(profiles.filter(p=>p.role==='student'&&p.status==='active').map(p=>({value:p.id,label:p.full_name??p.id}))),course_id:select(courses.filter(c=>c.status==='published').map(c=>({value:c.id,label:c.title})))},async values=>{await operate('enrollment',null,values);}),table(data.enrollments,[['student','Student'],['course','Course'],['status','Status'],['enrolled_at','Enrolled']],r=>r.status==='cancelled'?el('span',{},'Cancelled'):button('Cancel enrollment',async()=>{await operate('cancel_enrollment',str(r,'id'));reload();})));
 }
 if(section==='audit')content.append(table(data.audit,[['actor',"Administrator or user"],['action','Action'],['resource_type','Resource'],['created_at','Time']]));
 if(section==='live')content.append(el('div',{class:'btn-row'},el('a',{href:'/admin/moderation/',class:'btn'},'Review class requests')),table(data.classes,[['title','Class'],['course','Course'],['platform','Platform'],['scheduled_date','Date'],['start_time','Start'],['timezone','Timezone'],['status','Status']],r=>selectAction(r)));
 if(section==='moderation'){
  const [courses,applications]=await Promise.all([reviewQueueCourses(),tutorApplications()]);
  content.append(el('p',{class:'admin-page-description'},'Review tutor applications and course submissions, then resolve live class requests and reported content.'),el('h2',{},"Tutor applications"),table(applications.filter(a=>a.status==='pending') as unknown as AdminRow[],[['full_name','Applicant'],['headline','Specialty'],['created_at','Submitted']],r=>el('a',{class:'btn btn--sm',href:`/admin/review/?application=${encodeURIComponent(str(r,'id'))}`},'Review application')),el('h2',{},"Course submissions"),table(courses as unknown as AdminRow[],[['title','Course'],['status','Status']],r=>el('a',{class:'btn btn--sm',href:`/admin/review/?course=${encodeURIComponent(str(r,'id'))}`},'Review course'))); 
  const decision=(kind:string,r:AdminRow,choices:[string,string][])=>{const note=textarea({maxlength:2000,rows:2,placeholder:'Review note', 'aria-label':`Review note for ${str(r,'title')==='—'?str(r,'course'):str(r,'title')}`});return el('div',{},note,el('div',{class:'btn-row'},...choices.map(([status,label])=>button(label,async()=>{await operate(kind,str(r,'id'),{status,note:note.value.trim()||null});reload();}))));};
  content.append(el('a',{href:'/admin/review/',class:'btn'},'Review tutor applications & courses'),el('h2',{},"Live class requests"),table(data.requests,[['title','Class'],['status','Status'],['created_at','Requested']],r=>r.status==='pending'?decision('request_decision',r,[['approved','Approve'],['rejected','Reject']]):el('span',{},'Reviewed')),el('h2',{},"Content reports"),table(data.reports,[['course','Course'],['reason','Reported issue'],['status','Status'],['resolution','Resolution']],r=>r.status==='open'?decision('report_decision',r,[['resolved','Resolve'],['dismissed','Dismiss']]):el('span',{},'Reviewed')));
 }
 if(section==='payments'){
  const [profiles,courses]=await Promise.all([listProfiles(),listCourses()]);const students=profiles.filter(p=>p.role==='student');
  content.append(el('p',{},"Record confirmed payments or refunds in naira. This page only keeps records. It does not take or send money. Saved entries cannot be changed. Add a refund entry to correct a payment."),formPanel('Record payment or refund',{student_id:select(students.map(p=>({value:p.id,label:p.full_name??p.id}))),course_id:select([{value:'',label:'No course specified'},...courses.map(c=>({value:c.id,label:c.title}))]),amount:input({type:'number',min:'0.01',max:'1000000000',step:'0.01',required:true}),kind:select([{value:'payment',label:'Payment'},{value:'refund',label:'Refund'}]),reference:input({required:true,minlength:3,maxlength:120,placeholder:'Unique receipt or refund reference'}),note:textarea({maxlength:1000})},async v=>{await operate('payment',null,{...v,amount_minor:Math.round(Number(v.amount)*100)});}),table(data.payments,[['student','Student'],['kind','Type'],['amount_minor','Amount (NGN)'],['reference','Reference'],['created_at','Recorded']]));
  const hub=await learningWorkspace();
  content.append(el('h2',{},'Tutor Earnings'),el('p',{},"Record a tutor’s share of a confirmed course payment, reverse an earlier entry or record a payment made outside the app. Choose a receipt when recording earnings. Choose the original entry when reversing earnings. Leave both fields blank for a completed payment."),formPanel('Record tutor earnings',{tutor_id:select(profiles.filter(p=>p.role==='tutor'&&p.status==='active').map(p=>({value:p.id,label:p.full_name??p.id}))),kind:select([{value:'earning',label:'Earning allocation'},{value:'reversal',label:'Reverse earning'},{value:'payout',label:'Completed payout'}]),amount:input({type:'number',min:'0.01',max:'1000000000',step:'0.01',required:true}),reference:input({required:true,minlength:3,maxlength:120}),payment_id:select([{value:'',label:'No receipt'},...data.payments.filter(r=>r.kind==='payment'&&r.course_id).map(r=>({value:str(r,'id'),label:`${str(r,'reference')}: ${money(Number(r.amount_minor)/100)}`}))]),original_entry_id:select([{value:'',label:'No original entry'},...hub.earnings.filter(r=>r.kind==='earning').map(r=>({value:str(r,'id'),label:str(r,'reference')}))]),note:textarea({maxlength:1000})},recordEarning),table(hub.earnings,[['tutor_id','Tutor ID'],['kind','Type'],['amount_minor','Amount (NGN)'],['reference','Reference'],['created_at','Recorded']]));

 }
 if(section==='messages'){
  const profiles=await listProfiles();content.append(formPanel("Send message in the app",{recipient_id:select(profiles.filter(p=>p.status==='active').map(p=>({value:p.id,label:p.full_name??p.id}))),subject:input({required:true,maxlength:200}),body:textarea({required:true,maxlength:5000})},async v=>{await operate('message',null,v);}),table(data.messages,[['sender','From'],['recipient','To'],['subject','Subject'],['body','Message'],['created_at','Time']],r=>r.read_at || r.recipient_id!==session.profile.id?el('span',{},r.read_at?'Read':'Sent'):button("Mark as read",async()=>{if(config.preview)throw new Error("Changes cannot be saved until the app has a database connection.");await unwrap(supabase().from('inbox_messages').update({read_at:new Date().toISOString()}).eq('id',str(r,'id')));reload();})));
 }
 if(section==='settings'){
  content.append(formPanel('Platform settings',{key:select(['site_name','support_email','default_timezone','maintenance_notice'].map(key=>({value:key,label:key.replaceAll('_',' ')}))),value:input({required:true,maxlength:1000})},async v=>{await operate('setting',null,v);}),table(data.settings,[['key','Setting'],['value','Value'],['updated_at','Updated']]));
 }
 if(section==='reports'){
  const range=dateRange();const start=input({type:'date',required:true,value:range.start});const end=input({type:'date',required:true,value:range.end});const reportArea=el('section',{class:'dash-card'});
  const show=async()=>{const metrics=await dateMetrics(start.value,end.value);setChildren(reportArea,table(metrics.labels.map((date,i)=>({date,students:metrics.students[i],enrollments:metrics.enrollments[i],revenue:money(metrics.revenue?.[i]??0)})),[['date','Date'],['students','New students'],['enrollments','Enrolments']]));};
  content.append(el('form',{class:'admin-date-form',onsubmit:(event:Event)=>{event.preventDefault();void action(show)(event);}},field('From',start),field('To',end),el('button',{type:'submit',class:'btn'},'Apply'),button('Generate CSV',async()=>{if(config.preview){downloadReport(await dateMetrics(start.value,end.value));toast("Demo report downloaded. Nothing was saved to the database.");return;}const result=await operate('report',null,{start:start.value,end:end.value});if(result.data)downloadReport(result.data);})),reportArea,el('h2',{},'Saved report history'),table(data.runs,[['start_date','From'],['end_date','To'],['created_at','Generated']],r=>button('Download CSV',async()=>{const result=await operate('download_report',str(r,'id'));if(result.data)downloadReport(result.data);})));await show();
 }
});
function selectAction(r:AdminRow):HTMLElement{const status=select(['scheduled','live','completed','cancelled'].map(value=>({value,label:value})));status.value=str(r,'status');return el('div',{class:'btn-row'},status,button('Update',async()=>{await setLiveClassStatus(str(r,'id'),status.value as 'scheduled'|'live'|'completed'|'cancelled');reload();}));}
