import {myEnrollments,coursesFor,myLessons,listModules,listMaterials,learningResourceUrl} from '../api.ts';
import {action,el,emptyState,page,setChildren} from '../ui.ts';
import type {LessonMaterial} from '../types.ts';
const pastQuestions=location.pathname.includes('assignments');
void page({role:'student',title:pastQuestions?"Past questions":"Study materials",base:'/student',active:pastQuestions?'/assignments/':'/materials/'},async content=>{
 const courses=await coursesFor((await myEnrollments()).filter(e=>e.status==='active').map(e=>e.course_id));
 const entries:{material:LessonMaterial;course:string;module:string;lesson:string}[]=[];
 for(const course of courses){const modules=await listModules(course.id);for(const lesson of await myLessons(course.id))for(const material of await listMaterials(lesson.id))if(pastQuestions?material.type==='practice_questions':material.type!=='practice_questions')entries.push({material,course:course.title,module:modules.find(m=>m.id===lesson.module_id)?.title??'Lessons',lesson:lesson.title});}
 entries.sort((a,b)=>(b.material.created_at??'').localeCompare(a.material.created_at??''));
 const card=(entry:typeof entries[number])=>el('article',{class:'card'},el('div',{class:'card__body'},el('h3',{},entry.material.title),el('p',{class:'learning-muted'},`${entry.course} · ${entry.module} · ${entry.lesson}`),el('button',{class:'btn',type:'button',onclick:action(async()=>{const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{let target=await learningResourceUrl(entry.material.storage_path);const link=new URL(target);const id=/\/file\/d\/([^/]+)/.exec(link.pathname)?.[1]??link.searchParams.get('id');if(link.hostname==='drive.google.com'&&id)target=`https://drive.google.com/uc?export=download&id=${encodeURIComponent(id)}`;if(tab)tab.location.href=target;else location.assign(target);}catch(error){tab?.close();throw error;}})},pastQuestions?'Download past questions':'Download material')));
 setChildren(content,el('h1',{},pastQuestions?"Past questions":"Study materials"),entries.length?el('section',{},el('h2',{},pastQuestions?'Newest past questions':'Newest materials'),el('div',{class:'app-grid app-grid--cards'},...entries.slice(0,6).map(card))):emptyState('No published study materials yet',"Materials appear here when your tutors publish them."),...courses.map(course=>el('section',{class:'card'},el('div',{class:'card__body'},el('h2',{},course.title),...[...new Set(entries.filter(e=>e.course===course.title).map(e=>e.module))].map(module=>el('details',{class:'student-module-library'},el('summary',{},module),...entries.filter(e=>e.course===course.title&&e.module===module).map(card)))))));
});
